# Generated by Django 5.2.9 on 2025-12-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticky_notes_app', '0002_rename_assigned_to_task_user_remove_task_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
